micronaut.application.name=micronaut-payments
micronaut.server.port=8092
datasources.default.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5436}/payments
datasources.default.username=payments
datasources.default.password=payments
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.dialect=POSTGRES
datasources.default.schema-generate=CREATE_DROP
